### ISSUE TITLE
Community/Getting Started does not mention Discourse at all

### ISSUE THREAD

**Issue by bbannier** [zeek/website#5]
The community documentation currently only very indirectly mentions our Discourse instance under Community→Connect→Discourse. The top-level documents still reference email, e.g., [Getting Started](https://zeek.org/getting-started-in-the-zeek-community/) or [Email Signup](https://zeek.org/sign-up/) linked from the Community menu.

We should probably retire the Email Signup page, and update to Getting Started page to reference Discourse instead of email.

**Comment by ckreibich** [comment]
Good catch. I made an edit pass over the Getting Started page, please feel free to take a look. I don't think we can stage changes without making it generally viewable or giving everyone Wordpress accounts, so I'm afraid that approach will have to do right now. (I'm certainly fine with handing out more Wordpress access — anything to get that site more maintained!)

Btw I removed all references to the old Bitly link for Slack signups because it breaks every time we need a new invite link. The only place where we currently replace it is on zeek.org/community.

I poked through Wordpress to see how we might ditch the signup page but I'm worried I'll break something in the god-awful Divi editor. We can sort this out with the contractor maintaining the site. We need a contractor to remove a webpage. :facepalm:

**Comment by bbannier** [comment]
>  I made an edit pass over the Getting Started page, please feel free to take a look.

Thanks, this looks better. WDYT about inserting even more direct links, e.g.,

```patch
- A lot of our communication and discussion happens on our Discourse server and in our Slack workspace, 
+ A lot of our communication and discussion happens on our [Discourse server](https://community.zeek.org/) and in our [Slack workspace](https://join.slack.com/t/zeekorg/shared_invite/zt-21fvv0i80-7ZrkYiS4cJqI4FFQ6tomDQ), 
```

> I poked through Wordpress to see how we might ditch the signup page but I'm worried I'll break something in the god-awful Divi editor. We can sort this out with the contractor maintaining the site. We need a contractor to remove a webpage. 🤦

Let's keep this issue (or a narrower follow-up issue) open until this is fixed.

**Comment by ckreibich** [comment]
I agree with all, the only reason I didn't add more direct links is Slack with its unhelpful signup link policy — we need to figure out where to replace that link every time we get a new one. And, we regularly screw it up, because for example I never noticed it's also in the site footer, where it's currently broken. :-(

The contractor resolved the signup page, so as far as I'm concerned we can close this, but I'll leave it to you.

**Comment by timwoj** [comment]
I thought we had set up a redirect in AWS for the signup link. The website should link to that redirect, and we can fix it in one place if it needs changing. I think @0xxon set that up a while back.

**Comment by awelzel** [comment]
Ah yes, I wanted to comment. `zeek.org/slack` is the redirect. We use that one on docs.zeek.org.

https://docs.zeek.org/en/master/quickstart.html#next-steps

**Comment by timwoj** [comment]
> Ah yes, I wanted to comment. `zeek.org/slack` is the redirect. We use that one on docs.zeek.org.

Right, that's the one. We should be linking to that from the website as well, instead of the bare slack link.

**Comment by ckreibich** [comment]
Okay wow ... I think there's a bunch to address here. First, I had no idea about this. I'm sure I just missed it somewhere — sorry. :facepalm: 

Next — it looks like there are two things:
- https://zeek.org/slack/ — this is used in the docs and redirects me to https://zeek.org/slack-guidelines/ which doesn't let you sign up for Slack :-)
- https://zeek.org/slack — (no slash, really) this redirects me to https://zeekorg.slack.com/signup#/domain-signup, saying something about @tacc.utexus.edu???

We last got a new invite link in August. I [mentioned this](https://zeekorg.slack.com/archives/G01DBSH71KJ/p1691792658864929) in the team channel. That link is https://join.slack.com/t/zeekorg/shared_invite/zt-21fvv0i80-7ZrkYiS4cJqI4FFQ6tomDQ, which is what's currently linked from zeek.org/community.

So I think we should do the following:
- Drop that zeek.org/slack/ redirect to the guidelines — not sure it accomplishes much?
- Fix zeek.org/slack to use the new invite link — who can do this?
- Ideally make sure that zeek.org/slack and zeek.org/slack/ behave the same because that will clearly go wrong again?
- Do an edit pass over the site to use zeek.org/slack

Yes?

All of this because of their boneheaded expiring-invite-link policy, sigh...

**Comment by ckreibich** [comment]
I think this is all resolved now:

- The docs now use zeek.org/slack via the linked PR
- Given that handy zeek.org/slack redirect I've expanded the links on the getting-started page as per @bbannier's suggestion
- `/slack/` now redirects to `/slack` — the previous redirect to the Slack Guidelines page didn't make much sense because the header/footer links to the Slack Guidelines link to the [equivalent page](https://github.com/zeek/zeek/wiki/Slack-Guidelines) in the Zeek Wiki, not the zeek.org page
- The website now uses zeek.org/slack in header, footer, and on the community page

I'm closing the ticket.
