### ISSUE TITLE
GithHub icon in footer and Copyright date

### ISSUE THREAD

**Issue by awelzel** [zeek/website#6]
I was at a small local event, chatted about Zeek, got someone interested. He browsed to zeek.org to find its way to GitHub. Instinctively scrolled all the way down and immediately and drily said: "Copyright 2020, no GitHub icon".

Might also be nice to put an icon to the forum there.

![84483](https://github.com/zeek/website/assets/2100509/309090e7-511f-433c-abed-a9910ea445bb)

**Comment by ckreibich** [comment]
Somebody (likely @0xxon or our contractor) recently updated the year — it does now say 2024.

I figured out that the social icons are implied by the theme we're using, and I don't immediately see any way to add to them. There's a checkbox that toggles their visibility in total, though, and since we're already listing all the social sites in the footer I simply unchecked that for now.
